/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.8.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package client

// ScaleSpec describes the attributes of a scale subresource
type AppsV1beta1ScaleSpec struct {

	// desired number of instances for the scaled object.
	Replicas int32 `json:"replicas,omitempty"`
}
