/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.8.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package client

// DEPRECATED.
type ExtensionsV1beta1RollbackConfig struct {

	// The revision to rollback to. If set to 0, rollback to the last revision.
	Revision int64 `json:"revision,omitempty"`
}
