/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.8.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package client

// AttachedVolume describes a volume attached to a node
type V1AttachedVolume struct {

	// DevicePath represents the device path where the volume should be available
	DevicePath string `json:"devicePath"`

	// Name of the attached volume
	Name string `json:"name"`
}
