/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.8.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package client

// Information about the condition of a component.
type V1ComponentCondition struct {

	// Condition error code for a component. For example, a health check error code.
	Error_ string `json:"error,omitempty"`

	// Message about the condition for a component. For example, information about a health check.
	Message string `json:"message,omitempty"`

	// Status of the condition for a component. Valid values for \"Healthy\": \"True\", \"False\", or \"Unknown\".
	Status string `json:"status"`

	// Type of condition for a component. Valid value: \"Healthy\"
	Type_ string `json:"type"`
}
