/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.8.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package client

// Adds and removes POSIX capabilities from running containers.
type V1Capabilities struct {

	// Added capabilities
	Add []string `json:"add,omitempty"`

	// Removed capabilities
	Drop []string `json:"drop,omitempty"`
}
