/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.8.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package client

// ContainerStateWaiting is a waiting state of a container.
type V1ContainerStateWaiting struct {

	// Message regarding why the container is not yet running.
	Message string `json:"message,omitempty"`

	// (brief) reason the container is not yet running.
	Reason string `json:"reason,omitempty"`
}
