/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.8.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package client

// DaemonEndpoint contains information about a single Daemon endpoint.
type V1DaemonEndpoint struct {

	// Port number of the given endpoint.
	Port int32 `json:"Port"`
}
