/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.8.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package client

// Represents downward API info for projecting into a projected volume. Note that this is identical to a downwardAPI volume source without the default mode.
type V1DownwardApiProjection struct {

	// Items is a list of DownwardAPIVolume file
	Items []V1DownwardApiVolumeFile `json:"items,omitempty"`
}
