/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.8.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package client

// EnvFromSource represents the source of a set of ConfigMaps
type V1EnvFromSource struct {

	// The ConfigMap to select from
	ConfigMapRef V1ConfigMapEnvSource `json:"configMapRef,omitempty"`

	// An optional identifer to prepend to each key in the ConfigMap. Must be a C_IDENTIFIER.
	Prefix string `json:"prefix,omitempty"`

	// The Secret to select from
	SecretRef V1SecretEnvSource `json:"secretRef,omitempty"`
}
