/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.8.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package client

// Initializer is information about an initializer that has not yet completed.
type V1Initializer struct {

	// name of the process that is responsible for initializing this object.
	Name string `json:"name"`
}
