/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.8.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package client

// LimitRangeSpec defines a min/max usage limit for resources that match on kind.
type V1LimitRangeSpec struct {

	// Limits is the list of LimitRangeItem objects that are enforced.
	Limits []V1LimitRangeItem `json:"limits"`
}
