/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.8.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package client

// NodeDaemonEndpoints lists ports opened by daemons running on the Node.
type V1NodeDaemonEndpoints struct {

	// Endpoint on which Kubelet is listening.
	KubeletEndpoint V1DaemonEndpoint `json:"kubeletEndpoint,omitempty"`
}
