/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.8.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package client

// NodeAddress contains information for the node's address.
type V1NodeAddress struct {

	// The node address.
	Address string `json:"address"`

	// Node address type, one of Hostname, ExternalIP or InternalIP.
	Type_ string `json:"type"`
}
