/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.8.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package client

// NetworkPolicyPort describes a port to allow traffic on
type V1NetworkPolicyPort struct {

	// The port on the given protocol. This can either be a numerical or named port on a pod. If this field is not provided, this matches all port names and numbers.
	Port interface{} `json:"port,omitempty"`

	// The protocol (TCP or UDP) which traffic must match. If not specified, this field defaults to TCP.
	Protocol string `json:"protocol,omitempty"`
}
