/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.8.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package client

// ObjectFieldSelector selects an APIVersioned field of an object.
type V1ObjectFieldSelector struct {

	// Version of the schema the FieldPath is written in terms of, defaults to \"v1\".
	ApiVersion string `json:"apiVersion,omitempty"`

	// Path of the field to select in the specified API version.
	FieldPath string `json:"fieldPath"`
}
