/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.8.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package client

// Preconditions must be fulfilled before an operation (update, delete, etc.) is carried out.
type V1Preconditions struct {

	// Specifies the target UID.
	Uid string `json:"uid,omitempty"`
}
