/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.8.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package client

// ResourceQuotaStatus defines the enforced hard limits and observed use.
type V1ResourceQuotaStatus struct {

	// Hard is the set of enforced hard limits for each named resource. More info: https://git.k8s.io/community/contributors/design-proposals/admission_control_resource_quota.md
	Hard map[string]string `json:"hard,omitempty"`

	// Used is the current observed total usage of the resource in the namespace.
	Used map[string]string `json:"used,omitempty"`
}
