/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.8.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package client

type V1SelfSubjectRulesReviewSpec struct {

	// Namespace to evaluate rules for. Required.
	Namespace string `json:"namespace,omitempty"`
}
