/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.8.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package client

// SecretReference represents a Secret Reference. It has enough information to retrieve secret in any namespace
type V1SecretReference struct {

	// Name is unique within a namespace to reference a secret resource.
	Name string `json:"name,omitempty"`

	// Namespace defines the space within which the secret name must be unique.
	Namespace string `json:"namespace,omitempty"`
}
