/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.8.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package client

// ScaleIOVolumeSource represents a persistent ScaleIO volume
type V1ScaleIoVolumeSource struct {

	// Filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. \"ext4\", \"xfs\", \"ntfs\". Implicitly inferred to be \"ext4\" if unspecified.
	FsType string `json:"fsType,omitempty"`

	// The host address of the ScaleIO API Gateway.
	Gateway string `json:"gateway"`

	// The name of the Protection Domain for the configured storage (defaults to \"default\").
	ProtectionDomain string `json:"protectionDomain,omitempty"`

	// Defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts.
	ReadOnly bool `json:"readOnly,omitempty"`

	// SecretRef references to the secret for ScaleIO user and other sensitive information. If this is not provided, Login operation will fail.
	SecretRef V1LocalObjectReference `json:"secretRef"`

	// Flag to enable/disable SSL communication with Gateway, default false
	SslEnabled bool `json:"sslEnabled,omitempty"`

	// Indicates whether the storage for a volume should be thick or thin (defaults to \"thin\").
	StorageMode string `json:"storageMode,omitempty"`

	// The Storage Pool associated with the protection domain (defaults to \"default\").
	StoragePool string `json:"storagePool,omitempty"`

	// The name of the storage system as configured in ScaleIO.
	System string `json:"system"`

	// The name of a volume already created in the ScaleIO system that is associated with this volume source.
	VolumeName string `json:"volumeName,omitempty"`
}
