/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.8.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package client

// TokenReviewStatus is the result of the token authentication request.
type V1TokenReviewStatus struct {

	// Authenticated indicates that the token was associated with a known user.
	Authenticated bool `json:"authenticated,omitempty"`

	// Error indicates that the token couldn't be checked
	Error_ string `json:"error,omitempty"`

	// User is the UserInfo associated with the provided token.
	User V1UserInfo `json:"user,omitempty"`
}
