/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.8.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package client

// ExternalAdmissionHook describes an external admission webhook and the resources and operations it applies to.
type V1alpha1ExternalAdmissionHook struct {

	// ClientConfig defines how to communicate with the hook. Required
	ClientConfig V1alpha1AdmissionHookClientConfig `json:"clientConfig"`

	// FailurePolicy defines how unrecognized errors from the admission endpoint are handled - allowed values are Ignore or Fail. Defaults to Ignore.
	FailurePolicy string `json:"failurePolicy,omitempty"`

	// The name of the external admission webhook. Name should be fully qualified, e.g., imagepolicy.kubernetes.io, where \"imagepolicy\" is the name of the webhook, and kubernetes.io is the name of the organization. Required.
	Name string `json:"name"`

	// Rules describes what operations on what resources/subresources the webhook cares about. The webhook cares about an operation if it matches _any_ Rule.
	Rules []V1alpha1RuleWithOperations `json:"rules,omitempty"`
}
