/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.8.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package client

// ServiceReference holds a reference to Service.legacy.k8s.io
type V1alpha1ServiceReference struct {

	// Name is the name of the service Required
	Name string `json:"name"`

	// Namespace is the namespace of the service Required
	Namespace string `json:"namespace"`
}
