/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.8.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package client

// RoleRef contains information that points to the role being used
type V1alpha1RoleRef struct {

	// APIGroup is the group for the resource being referenced
	ApiGroup string `json:"apiGroup"`

	// Kind is the type of resource being referenced
	Kind string `json:"kind"`

	// Name is the name of resource being referenced
	Name string `json:"name"`
}
