/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.8.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package client

// AdmissionHookClientConfig contains the information to make a TLS connection with the webhook
type V1alpha1AdmissionHookClientConfig struct {

	// CABundle is a PEM encoded CA bundle which will be used to validate webhook's server certificate. Required
	CaBundle string `json:"caBundle"`

	// Service is a reference to the service for this webhook. If there is only one port open for the service, that port will be used. If there are multiple ports open, port 443 will be used if it is open, otherwise it is an error. Required
	Service V1alpha1ServiceReference `json:"service"`
}
