/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.8.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package client

// CustomResourceDefinitionSpec describes how a user wants their resource to appear
type V1beta1CustomResourceDefinitionSpec struct {

	// Group is the group this resource belongs in
	Group string `json:"group"`

	// Names are the names used to describe this custom resource
	Names V1beta1CustomResourceDefinitionNames `json:"names"`

	// Scope indicates whether this resource is cluster or namespace scoped.  Default is namespaced
	Scope string `json:"scope"`

	// Validation describes the validation methods for CustomResources This field is alpha-level and should only be sent to servers that enable the CustomResourceValidation feature.
	Validation V1beta1CustomResourceValidation `json:"validation,omitempty"`

	// Version is the version this resource belongs in
	Version string `json:"version"`
}
