/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.8.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package client

// Run A sUser Strategy Options defines the strategy type and any options used to create the strategy.
type V1beta1RunAsUserStrategyOptions struct {

	// Ranges are the allowed ranges of uids that may be used.
	Ranges []V1beta1IdRange `json:"ranges,omitempty"`

	// Rule is the strategy that will dictate the allowable RunAsUser values that may be set.
	Rule string `json:"rule"`
}
