/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.8.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package client

type V1beta1DaemonSetUpdateStrategy struct {

	// Rolling update config params. Present only if type = \"RollingUpdate\".
	RollingUpdate V1beta1RollingUpdateDaemonSet `json:"rollingUpdate,omitempty"`

	// Type of daemon set update. Can be \"RollingUpdate\" or \"OnDelete\". Default is OnDelete.
	Type_ string `json:"type,omitempty"`
}
