/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.8.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package client

// NonResourceAttributes includes the authorization attributes available for non-resource requests to the Authorizer interface
type V1beta1NonResourceAttributes struct {

	// Path is the URL path of the request
	Path string `json:"path,omitempty"`

	// Verb is the standard HTTP verb
	Verb string `json:"verb,omitempty"`
}
