/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.8.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package client

// RollingUpdateStatefulSetStrategy is used to communicate parameter for RollingUpdateStatefulSetStrategyType.
type V1beta1RollingUpdateStatefulSetStrategy struct {

	// Partition indicates the ordinal at which the StatefulSet should be partitioned.
	Partition int32 `json:"partition,omitempty"`
}
