/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.8.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package client

type V1beta1NetworkPolicyPeer struct {

	// IPBlock defines policy on a particular IPBlock
	IpBlock V1beta1IpBlock `json:"ipBlock,omitempty"`

	// Selects Namespaces using cluster scoped-labels.  This matches all pods in all namespaces selected by this label selector. This field follows standard label selector semantics. If present but empty, this selector selects all namespaces.
	NamespaceSelector V1LabelSelector `json:"namespaceSelector,omitempty"`

	// This is a label selector which selects Pods in this namespace. This field follows standard label selector semantics. If present but empty, this selector selects all pods in this namespace.
	PodSelector V1LabelSelector `json:"podSelector,omitempty"`
}
