/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.8.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package client

// Host Port Range defines a range of host ports that will be enabled by a policy for pods to use.  It requires both the start and end to be defined.
type V1beta1HostPortRange struct {

	// max is the end of the range, inclusive.
	Max int32 `json:"max"`

	// min is the start of the range, inclusive.
	Min int32 `json:"min"`
}
