/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.8.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package client

// CustomResourceDefinitionStatus indicates the state of the CustomResourceDefinition
type V1beta1CustomResourceDefinitionStatus struct {

	// AcceptedNames are the names that are actually being used to serve discovery They may be different than the names in spec.
	AcceptedNames V1beta1CustomResourceDefinitionNames `json:"acceptedNames"`

	// Conditions indicate state for particular aspects of a CustomResourceDefinition
	Conditions []V1beta1CustomResourceDefinitionCondition `json:"conditions"`
}
