/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.8.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package client

// ExternalDocumentation allows referencing an external resource for extended documentation.
type V1beta1ExternalDocumentation struct {

	Description string `json:"description,omitempty"`

	Url string `json:"url,omitempty"`
}
