/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.8.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package client

// DeploymentStrategy describes how to replace existing pods with new ones.
type V1beta2DeploymentStrategy struct {

	// Rolling update config params. Present only if DeploymentStrategyType = RollingUpdate.
	RollingUpdate V1beta2RollingUpdateDeployment `json:"rollingUpdate,omitempty"`

	// Type of deployment. Can be \"Recreate\" or \"RollingUpdate\". Default is RollingUpdate.
	Type_ string `json:"type,omitempty"`
}
