/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.8.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package client

// SELinux  Strategy Options defines the strategy type and any options used to create the strategy.
type V1beta1SeLinuxStrategyOptions struct {

	// type is the strategy that will dictate the allowable labels that may be set.
	Rule string `json:"rule"`

	// seLinuxOptions required to run as; required for MustRunAs More info: https://git.k8s.io/community/contributors/design-proposals/security_context.md
	SeLinuxOptions V1SeLinuxOptions `json:"seLinuxOptions,omitempty"`
}
