/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.8.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package client

// FSGroupStrategyOptions defines the strategy type and options used to create the strategy.
type V1beta1FsGroupStrategyOptions struct {

	// Ranges are the allowed ranges of fs groups.  If you would like to force a single fs group then supply a single range with the same start and end.
	Ranges []V1beta1IdRange `json:"ranges,omitempty"`

	// Rule is the strategy that will dictate what FSGroup is used in the SecurityContext.
	Rule string `json:"rule,omitempty"`
}
