/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.8.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package client

// MetricSpec specifies how to scale based on a single metric (only `type` and one other matching field should be set at once).
type V2beta1MetricSpec struct {

	// object refers to a metric describing a single kubernetes object (for example, hits-per-second on an Ingress object).
	Object V2beta1ObjectMetricSource `json:"object,omitempty"`

	// pods refers to a metric describing each pod in the current scale target (for example, transactions-processed-per-second).  The values will be averaged together before being compared to the target value.
	Pods V2beta1PodsMetricSource `json:"pods,omitempty"`

	// resource refers to a resource metric (such as those specified in requests and limits) known to Kubernetes describing each pod in the current scale target (e.g. CPU or memory). Such metrics are built in to Kubernetes, and have special scaling options on top of those available to normal per-pod metrics using the \"pods\" source.
	Resource V2beta1ResourceMetricSource `json:"resource,omitempty"`

	// type is the type of metric source.  It should match one of the fields below.
	Type_ string `json:"type"`
}
