/* 
 * Kubernetes
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.8.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package client

// PodsMetricSource indicates how to scale on a metric describing each pod in the current scale target (for example, transactions-processed-per-second). The values will be averaged together before being compared to the target value.
type V2beta1PodsMetricSource struct {

	// metricName is the name of the metric in question
	MetricName string `json:"metricName"`

	// targetAverageValue is the target value of the average of the metric across all relevant pods (as a quantity)
	TargetAverageValue string `json:"targetAverageValue"`
}
